### ISSUE TITLE
Expand array capabilities with foreach

### ISSUE THREAD

**Issue by aoeah** [JTranOrg/JTran#40]
First off, thank you for adding in the ability to describe an array!  I think that the functionality could be enhanced even further if you can use foreach within an array.  I could see this being used in two separate ways.  Both would require you to NOT provide the second optional parameter, however, as you are not within the scope of an object.

**1) Combining lists together**
A person could create a transform such as
`{
    "ShoppingList": [
       "#foreach(Ingredients)": {
           "DisplayName": "#(Name)",
           "Qty: "#(Qty)"
       },
       "#foreach(RequiredEquipment)": {
            "DisplayName": "#(Name)"
            "Qty": 1
      }
    ]
}`

from a body such as
`{
   Ingredients: [
     { Name: "Apples", Qty: 10 }
     { Name: "Chocolate", Qty: 1 }
  ],
  RequiredEquipment: [
    { Name: "Blender" },
    { Name: "Spatula" }
  ]
}`

**2) Building 2-dimensional arrays**
(I ran out of time to come up with an example, I'll try to come back around and provide an example)

**Comment by jim-lightfoot** [comment]
#1 is fixed. Added #array and #arrayitem

**Comment by jim-lightfoot** [comment]
Added support for 2 dimensional arrays. This can be done in the following way:

```
{
    "#array(Cars)":
    {
        "#arrayitem(1)":  "#($DomesticCars)",   // These vars refer to arrays
        "#arrayitem(2)":  "#($ForeignCars)",
        "#arrayitem(3)":  "#($CustomCars)"
    }
}
```

Then the output might look this:

```
{
   Cars:
    [
       [
          "Chevy",
          "Pontiac",
          "Dodge"
       ],
       [
          "Audi",
          "BMW",
          "Aston-Martin"
       ],
       [
          "X9-673",
          "W2-DHS"
       ]
    ]
}
```
