### ISSUE TITLE
DateTimeUtc() on a UTC date treats date as local

### ISSUE THREAD

**Issue by aoeah** [JTranOrg/JTran#41]
If I do (in version 2.1)

`{
	SomeDate: "2020-07-09T17:03:06.4762435Z"
}`

With the transform of

`{
	SomeDateUtc: "#(DateTimeUtc(SomeDate))"
}`

I end up with a result of

`{
  "SomeDateUtc": "2020-07-10T00:03:06.0000000Z"
}`

I would have expected the hours to not change.

**Comment by jim-lightfoot** [comment]
Fixed
