### ISSUE TITLE
Accessing property that doesn't exist under an array returns object instead of null

### ISSUE THREAD

**Issue by aoeah** [JTranOrg/JTran#44]
This is different behavior than existed in a previous version of JTran. 

Data:
`{
	"Data": {
		"Value": 9
	},
	"OtherData": [
		{
			"Value": 10,
			"InnerObj": {
				Item1: 90
			}
		}
	]
}`

Transform:
`{
	//Result: 9hi
	"#variable(something)": "#(Data.Value)",
	Something: "#($something + 'hi')",

	//Throws exception A variable with that name does not exist: something2
	//"#variable(something2)": "#(Data.NotThere)",
	//Something2: "#($something2 + 'hi')",

	//Result: "System.Collections.Generic.List`1[System.Object]hi"
	"#variable(something3)": "#(OtherData.NotThere)",
	Something3: "#($something3 + 'hi')",

	//Result: "System.Collections.Generic.List`1[System.Object]hi"
	"#variable(something4)": "#(OtherData[0].NotThere)",
	Something4: "#($something4 + 'hi')",

	//Result: System.ArgumentException: Could not determine JSON object type for type System.Collections.Generic.KeyValuePair`2
	//"#variable(something5)": "#(OtherData[0].NotThere)",
	//Something5: "#($something4)",

	//Result: "90hi"
	"#variable(something6)": "#(OtherData[0].InnerObj.Item1)",
	Something6: "#($something6 + 'hi')",

	//Result: "System.Collections.Generic.List`1[System.Object]hi"
	"#variable(something7)": "#(OtherData[0].InnerObj.Item2)",
	Something7: "#($something7 + 'hi')",
}`

Result:
`{
  "Something": "9hi",
  "Something3": "System.Collections.Generic.List`1[System.Object]hi",
  "Something4": "System.Collections.Generic.List`1[System.Object]hi",
  "Something6": "90hi",
  "Something7": "System.Collections.Generic.List`1[System.Object]hi"
}`

For example, previous versions (I'm not sure which version changed the behavior) would consider $something7 as null.  If I were to do something like
#($something7 == null ? 10 : 20)

Then I would get 10, however in the latest version I would get 20.

**Comment by jim-lightfoot** [comment]
Fixed
