### ISSUE TITLE
Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Dynamic.ExpandoObject'

### ISSUE THREAD

**Issue by rajeev-ayer** [JTranOrg/JTran#58]
Using version **2.4.0**

I am attempting to use the JTran library for transformation of JSON documents and the very basic transformations are not working.  
Here is what I am doing.

### Source Document
```
{
    "Car":
    {
       "Make": "Chevy",
       "Model": "Corvette"
    }
}
```

### Transform
```
{
  "Make": "#(Car.Make)"
}
```

### Expected Output
```
{
  "Make": "Chevy"
}
```

I have tried doing this with the following C# code and all of these produce the same error.

#### Option 1
```
  var transformer = new Transformer(stylesheet);
  var transformedString = transformer.Transform(jsonInput);

```

#### Option 2
```
  var transformer = new Transformer(stylesheet);
  var context = new TransformerContext { Arguments = new Dictionary<string, object>() };
  var transformedString = transformer.Transform(jsonInput, context);

```

#### Option 3
```
  var transformer = new Transformer(stylesheet, new object[] { });
  var context = new TransformerContext { Arguments = new Dictionary<string, object>() };
  var transformedString = transformer.Transform(jsonInput, context);

```

Can you please point me in the right direction if I am doing something wrong.

**Comment by jim-lightfoot** [comment]
@rajeev-ayer I was not able to reproduce your issue, however, I was using version 3.0.0 which I just uploaded. Could you try this new version and then if you still have issues could you please include your complete code and I'll try that.
